language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

install:
  - travis_retry pip install -q -r requirements.txt
  - python setup.py -q install

script:
  - python --version
  - nosetests
  - behave -f progress --junit --tags=~@xfail features/
  - behave -f progress --junit --tags=~@xfail tools/test-features/
  - behave -f progress --junit --tags=~@xfail issue.features/

# -- USE: New container-based infrastructure for faster startup.
#    http://docs.travis-ci.com/user/workers/container-based-infrastructure/
# SEE ALSO: http://lint.travis-ci.org
